//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpfmain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=DESKTOP-BEQTQ1J;Database=IAN1;Integrated Security=True;Encrypt=False;User " +
            "Id=DESKTOP-BEQTQ1J\\ianch;")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
            set {
                this["ConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-BEQTQ1J;Initial Catalog=Northwind;Integrated Security=True;Co" +
            "nnect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=Re" +
            "adWrite;MultiSubnetFailover=False\"")]
        public string NorthwindConnectionString {
            get {
                return ((string)(this["NorthwindConnectionString"]));
            }
            set {
                this["NorthwindConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DESKTOP-BEQTQ1J\\ianch")]
        public string Machine_ID {
            get {
                return ((string)(this["Machine_ID"]));
            }
            set {
                this["Machine_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-BEQTQ1J;Initial Catalog=AdventureWorks2019;Integrated Securit" +
            "y=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;Application" +
            "Intent=ReadWrite;MultiSubnetFailover=False\"")]
        public string AdventureWorks2019 {
            get {
                return ((string)(this["AdventureWorks2019"]));
            }
            set {
                this["AdventureWorks2019"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-BEQTQ1J;Initial Catalog=IAN1;Integrated Security=True;Connect" +
            " Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWri" +
            "te;MultiSubnetFailover=False\"")]
        public string BankSysConnectionString {
            get {
                return ((string)(this["BankSysConnectionString"]));
            }
            set {
                this["BankSysConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRUE")]
        public string ReplaceFldNames {
            get {
                return ((string)(this["ReplaceFldNames"]));
            }
            set {
                this["ReplaceFldNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRUE")]
        public string UseFlowDoc {
            get {
                return ((string)(this["UseFlowDoc"]));
            }
            set {
                this["UseFlowDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string UseMagnify {
            get {
                return ((string)(this["UseMagnify"]));
            }
            set {
                this["UseMagnify"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W:\\\\WpfMain\\bin\\\\Debug\\\\")]
        public string AppRootPath {
            get {
                return ((string)(this["AppRootPath"]));
            }
            set {
                this["AppRootPath"] = value;
            }
        }
    }
}
